export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const SCORES_REQUEST = "SCORES_REQUEST";
export const SCORES_SUCCESS = "SCORES_SUCCESS";
export const SCORES_FAILURE = "SCORES_FAILURE";
